import{a as u,S as y,i as d}from"./assets/vendor-d74cd0e0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const E="gallery-link";function h({largeImageURL:r,tags:o,webformatURL:i,likes:a,views:e,comments:t,downloads:s}){return`
    <a href="${r}" class="${E}">
      <figure>
        <img src="${i}" alt="${o}" class="gallery-image">
        <figcaption class="gallery__figcaption">
          <div class="image-item">Likes <span class="image-elem">${a}</span></div>
          <div class="image-item">Views <span class="image-elem">${e}</span></div>
          <div class="image-item">Comments <span class="image-elem">${t}</span></div>
          <div class="image-item">Downloads <span class="image-elem">${s}</span></div>
        </figcaption>
      </figure>
    </a>
  `}const m=document.querySelector("#gallery"),p=document.querySelector(".search-form"),b=document.querySelector(".loader"),f=document.getElementById("loadMoreBtn"),L=document.getElementById("endMessage");let n=1,l="";function M(){m.innerHTML=""}function c(){f.style.display="none"}function $(){f.style.display="block"}function S(){L.style.display="none"}function q(){L.style.display="block"}function w(){b.style.display="inline-block"}function v(){b.style.display="none"}function g(r){d.info({title:"Information",message:r,position:"topRight"})}p.addEventListener("submit",async function(r){if(r.preventDefault(),l=r.target.elements.query.value,l!==""){n=1,M(),S(),w();try{const{data:o}=await u.get(`https://pixabay.com/api/?key=42404284-d1db8811507a6ab98b0e3f497&q=${l}&image_type=photo&orientation=horizontal&safeSearch=true&page=${n}&per_page=15`),{hits:i,totalHits:a}=o;if(i.length>0){const e=i.map(h).join("");m.innerHTML=e,new y(".gallery a").refresh(),$(),window.scrollBy({top:window.innerHeight,behavior:"smooth"})}else g("Sorry, there are no images matching your search query. Please try again!"),c()}catch(o){console.error("Error fetching images:",o),d.error({title:"Error",message:`Error fetching images: ${o.message}`,position:"topRight"})}finally{v(),p.reset()}}});f.addEventListener("click",async function(){w();try{const{data:r}=await u.get(`https://pixabay.com/api/?key=42404284-d1db8811507a6ab98b0e3f497&q=${l}&image_type=photo&orientation=horizontal&safeSearch=true&page=${n}&per_page=15`),{hits:o,totalHits:i}=r;if(o.length>0){const a=o.map(h).join("");m.innerHTML+=a,new y(".gallery a").refresh(),n++,window.scrollBy({top:window.innerHeight,behavior:"smooth"}),n*15>=i&&(q(),c(),g("Sorry, there are no more images to load."))}else g("Sorry, there are no more images to load."),c()}catch(r){console.error("Error fetching images:",r),d.error({title:"Error",message:`Error fetching images: ${r.message}`,position:"topRight"})}finally{v()}});
//# sourceMappingURL=commonHelpers.js.map
