import{a as y,S as h,i as d}from"./assets/vendor-64b55ca9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const m="gallery-link";function b({largeImageURL:r,tags:o,webformatURL:i,likes:s,views:e,comments:t,downloads:a}){return`
    <a href="${r}" class="${m}">
      <figure>
        <img src="${i}" alt="${o}" class="gallery-image">
        <figcaption class="gallery__figcaption">
          <div class="image-item">Likes <span class="image-elem">${s}</span></div>
          <div class="image-item">Views <span class="image-elem">${e}</span></div>
          <div class="image-item">Comments <span class="image-elem">${t}</span></div>
          <div class="image-item">Downloads <span class="image-elem">${a}</span></div>
        </figcaption>
      </figure>
    </a>
  `}const f=document.querySelector("#gallery"),p=document.querySelector(".search-form"),L=document.querySelector(".loader"),u=document.getElementById("loadMoreBtn"),$=document.getElementById("endMessage");let n=1,l="";function M(){f.innerHTML=""}function c(){u.style.display="none"}function v(){u.style.display="block"}function S(){$.style.display="none"}function q(){$.style.display="block"}function w(){L.style.display="inline-block"}function E(){L.style.display="none"}function g(r){d.info({title:"Information",message:r,position:"topRight"})}p.addEventListener("submit",async function(r){if(r.preventDefault(),l=r.target.elements.query.value,l!==""){n=1,M(),S(),w();try{const{data:o}=await y.get(`https://pixabay.com/api/?key=42404284-d1db8811507a6ab98b0e3f497&q=${l}&image_type=photo&orientation=horizontal&safeSearch=true&page=${n}&per_page=15`),{hits:i,totalHits:s}=o;if(i.length>0){const e=i.map(b).join("");f.innerHTML=e,new h(`.${m}`).refresh(),v()}else g("Sorry, there are no images matching your search query. Please try again!"),c()}catch(o){console.error("Error fetching images:",o),d.error({title:"Error",message:`Error fetching images: ${o.message}`,position:"topRight"})}finally{E(),p.reset()}}});u.addEventListener("click",async function(){w();try{const{data:r}=await y.get(`https://pixabay.com/api/?key=42404284-d1db8811507a6ab98b0e3f497&q=${l}&image_type=photo&orientation=horizontal&safeSearch=true&page=${n}&per_page=15`),{hits:o,totalHits:i}=r;if(o.length>0){const s=o.map(b).join("");f.innerHTML+=s,new h(`.${m}`).refresh(),n++;const t=window.innerHeight/2;window.scrollBy({top:t,behavior:"smooth"}),n*15>=i&&(q(),c(),g("Sorry, there are no more images to load."))}else g("Sorry, there are no more images to load."),c()}catch(r){console.error("Error fetching images:",r),d.error({title:"Error",message:`Error fetching images: ${r.message}`,position:"topRight"})}finally{E()}});
//# sourceMappingURL=commonHelpers.js.map
